config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/home" => "pages#home"
  get "/galleries" => "pages#galleries"
  get "/photos" => "pages#photos"

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  delete "/login" => "sessions#destroy"

  get "/users/edit" => "users#edit", as: "edit_user"
  get "/tag/:tag" => "pages#photos", as: :tag
  get "/search/:category" => "pages#photos", as: "category"
  resources :users, except: [:edit] do
    resources :galleries
    resources :photos
    member do
      get :following, :followers
     end
  end

  get "/galleries/:id/photos/new" => "photos#new", :as => "new_gallery_photo"
  post "/galleries/:id/photos" => "photos#create", :as => "gallery_photos"
  get "/search" => "pages#photos"
  post "/photos" => "photos#create"

  resources :relationships, only: [:create, :destroy]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  first_name      :string
#  last_name       :string
#  email           :string
#  image           :text
#  password_digest :text
#  about           :text
#  city            :string
#  country         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, format: /\A\S+@\S+\z/,
            uniqueness: {case_sensitive: false}

  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :galleries, dependent: :destroy
  has_many :photos, dependent: :destroy

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: [:new, :create, :show]
  before_action :authorise, only: [:edit, :update]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:file].present?
     req = Cloudinary::Uploader.upload(params[:file])
     @user.image = req['public_id']
     end
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
   if params[:file].present?
     req = Cloudinary::Uploader.upload(params[:file])
     @user.image = req['public_id']
     @user.assign_attributes(user_params)
     @user.save
     redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def following
   @user = User.find(params[:id])
   @following = @user.following
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :image, :password,
                                 :password_confirmation, :country, :city, :about)
  end

  def set_user
    @user = @current_user
  end

  def authorise
    unless @current_user.present?
    flash[:error] = "You need to be logged in to do that"
    redirect_to login_path
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper

 def has_followers?(user)
   user.followers.count > 0
 end

 def is_following?(user)
   user.following.count > 0
 end

end

app/views/users/_follow.html.erb
<%= form_for(@current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "waves-effect waves-light btn" %>
    <% end %>

app/views/users/_form.html.erb
<div class="container center">
<% unless @user.errors.full_messages.empty? %>
   <ul>
    <% @user.errors.full_messages.each do |e| %>
       <li><%= e %></li>
     <% end %>
   </ul>
 <% end %>
 <div class="card-panel">

<%= form_for(@user, :html => {:multipart => true}) do |f| %>
 <p>
  <%= f.label :first_name %>
  <%= f.text_field :first_name, :required => true %>
 </p>
 <p>
  <%= f.label :last_name %>
  <%= f.text_field :last_name, :required => true %>
 </p>
 <p>
  <%= f.label :email %>
  <%= f.text_field :email, :required => true %>
 </p>
 <p>
  <%= f.label :city %>
  <%= f.text_field :city %>
 </p>
 <p>
  <%= f.label :country %>
  <%= f.text_field :country %>
 </p>
 <p>
  <%= f.label :about %>
  <%= f.text_field :about %>
 </p>
 <p>
  <%= f.label :image %>
 </p>
 <p>
  <%= f.cl_image_upload :image %>
 </p>
 <p>
  <%= f.label :password %>
  <%= f.password_field :password, :required => true %>
 </p>
 <p>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :required => true %>
 </p>
 <%= f.submit class:"waves-effect waves-light btn" %>
<% end %>
</div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(@current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
             <%= f.submit "Unfollow", class: "btn" %>
             <% end %>

app/views/users/edit.html.erb
<div class="container center">

<h3>Edit <%= full_name(@user) %></h3>

<%= render 'form' %>

</div>

app/views/users/followers.html.erb
<div class="container">
<h3 class="center">Followers</h3>

<div class="row">
    <% @followers.each do |f| %>
    <div class="col s2 offset-s3">
       <%= cl_image_tag f.image, class:"circle profile" %>
     </div>
    <div class="col s7">
       <h5> <%= link_to "#{full_name(f)}", f %></h5>
        <p><strong>Email:</strong> <%= f.email %></p>
        <p><strong>Country: </strong> <%= f.country %></p>
     </div>
    <% end %>
   </div>
</div>

app/views/users/following.html.erb
<div class="container">
<h3 class="center">Following</h3>

<div class="row">
    <% @following.each do |f| %>
    <div class="col s2 offset-s3">
       <%= cl_image_tag f.image, class:"circle profile" %>
     </div>
    <div class="col s7">
       <h5> <%= link_to "#{full_name(f)}", f %></h5>
        <p><strong>Email:</strong> <%= f.email %></p>
        <p><strong>Country: </strong> <%= f.country %></p>
     </div>
    <% end %>
   </div>
</div>

app/views/users/index.html.erb
<div class="container">
<h3 class="center">All Users</h3>

<div class="row">
    <% @users.each do |u| %>
    <div class="col s2 offset-s3">
       <%= cl_image_tag u.image, class:"circle profile" %>
     </div>
    <div class="col s7">
       <h5> <%= link_to "#{full_name(u)}", u %></h5>
        <p><strong>Email:</strong> <%= u.email %></p>
        <p><strong>Country: </strong> <%= u.country %></p>
     </div>
    <% end %>
   </div>
</div>

app/views/users/new.html.erb
<div class="container center">
<h3>New User</h3>

<%= render 'form' %>
</div>

app/views/users/show.html.erb
<div class="container center">

 <%= cl_image_tag @user.image, class:"circle full_profile" %></li>
<h3><%= full_name(@user) %></h3>
<div class="divider"></div>
<ul>
  <% if has_followers?(@user) %>
    <li class="links"><%= link_to("#{@user.followers.count} Followers", followers_user_path(@user) ) %></li>
   <% end %>

   <% if is_following?(@user) %>
     <li class="links"><%= link_to("#{@user.following.count} Following", following_user_path(@user) ) %></li>
   <% end %>
    <% if @user.photos.exists? %>
      <li class="links"><%= link_to("#{@user.photos.count} Photos", user_photos_path(@user) ) %></li>
    <% end %>
    <% if @user.galleries.exists? %>
      <li class="links"><%= link_to("#{@user.galleries.count} Galleries", user_galleries_path(@user) ) %></li>
    <% end %>
    <div class="divider"></div>
</ul>
  <p><%= @user.about %></p>

<ul>
  <li class="links"><i class="material-icons">email</i>  <%= @user.email %></li>
  <li class="links"><i class="material-icons">location_on</i> <%= @user.city %>,  <%= @user.country %></li>
</ul>

   <% unless current_user?(@user) %>
      <% if @current_user.following?(@user) %>
        <%= render 'unfollow' %>
      <% else %>
        <%= render 'follow' %>
      <% end %>
   <% end %>

  <% if current_user?(@user) %>
     <%= link_to "Edit User", edit_user_path, class:"waves-effect waves-light btn" %>
     <%= link_to "Delete User", @user, class:"waves-effect waves-light btn", :method => :delete,
     :data => {confirm: "Are you sure?"} %>
  <% end %>

</div>