config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/home" => "pages#home"
  get "/galleries" => "pages#galleries"
  get "/photos" => "pages#photos"

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  delete "/login" => "sessions#destroy"

  get "/users/edit" => "users#edit", as: "edit_user"
  get "/tag/:tag" => "pages#photos", as: :tag
  get "/search/:category" => "pages#photos", as: "category"
  resources :users, except: [:edit] do
    resources :galleries
    resources :photos
    member do
      get :following, :followers
     end
  end

  get "/galleries/:id/photos/new" => "photos#new", :as => "new_gallery_photo"
  post "/galleries/:id/photos" => "photos#create", :as => "gallery_photos"
  get "/search" => "pages#photos"
  post "/photos" => "photos#create"

  resources :relationships, only: [:create, :destroy]

end

app/views/pages/_photo_nav.html.erb
<nav class="nav-extended center white">
    <div class="nav-wrapper align row">
      <ul class="tabs">
        <li class="tab col s3 m3"></li>
        <li class="tab col s3 m2"><a href="#test1">Fresh</a></li>
        <li class="tab col s3 m2"><a class="active" href="#test2">Editors Choice</a></li>
        <li class="tab col s3 m2"><a href="#test4">Popular</a></li>
        <li class="tab col s3 m3"></li>
      </ul>
    </div>
  </nav>

app/views/pages/_tags.html.erb
<div class="tag_cloud">
  <% tag_cloud Photo.tag_counts, %w[s m l] do |tag, css_class| %>
    <div class ="chip">
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
    </div>
  <% end %>
</div>

app/views/pages/galleries.html.erb
<h3 class="center">All Galleries </h3>

<div class="row">
<% @all_galleries.each do |g| %>
   <div class="col s4">
    <div class="card">
      <div class="card-image">
        <% if gallery_photos?(g) %>
      <%= link_to( cl_image_tag(g.photos.first.image), user_gallery_path( g.user, g) ) %>
    <% else %>
      <%= link_to( cl_image_tag("photo_placeholder.png"), user_gallery_path( g.user, g) ) %>
    <% end %>
      <span class="card-title"><%= "#{g.title} - #{full_name(g.user)}" %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/pages/home.html.erb
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h4 class="header center white-text homeheader">Share, learn and be inspired</h4>
        <div class="row center">
          <h5 class="header white-text col s12 light lowheader">Home of the best photographs across the web</h5>
        </div>
        <div class="row center">
          <%=link_to "Get Started", new_user_path, class:"btn-large waves-effect waves-light teal lighten-1" %>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax">
<%= image_tag "http://res.cloudinary.com/dilipbtuu/image/upload/v1480563824/h6rcymmv7hhk3grw1ibz.jpg" %> </div>
  </div>

  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="material-icons">collections</i></h2>
            <h5 class="center">Share Photos</h5>

            <p class="light">Share your photos with family and friends or showcase your talents. With options to licence photos, develop portfolios and connect with the right audience, Maximum Exposure provides you with a platform to take your photography to the next level.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="material-icons">group</i></h2>
            <h5 class="center">Learn tips and tricks</h5>

            <p class="light">Connect with proffessional photographers and continue to learn. Showcasing tips and tricks from experts. Get great advice on all things photograpy, our friendly community are always happy to help out.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center"><i class="material-icons">camera</i></h2>
            <h5 class="center">Be inspired to take better photos</h5>

            <p class="light">View thousands of uploaded photos varying in category and style. Maximum Exposure has something for everyone. Give back and provide your own little piece of inspiration to the rest of the world. </p>
          </div>
        </div>
      </div>

    </div>
  </div>

app/views/pages/photos.html.erb
<div class="center">
  <%= render "photo_nav" %>
  <p><%= render 'tags' %></p>
</div>
<div class="row">
<% @all_photos.each do |p| %>
  <% if p.user %>
   <div class="col s4">
    <div class="card">
      <div class="card-image">
      <%= link_to( cl_image_tag(p.image), user_photo_path( p.user, p) ) %>
          <span class="card-title"><%= full_name(p.user) %></span>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>