config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/home" => "pages#home"
  get "/galleries" => "pages#galleries"
  get "/photos" => "pages#photos"

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  delete "/login" => "sessions#destroy"

  get "/users/edit" => "users#edit", as: "edit_user"
  get "/tag/:tag" => "pages#photos", as: :tag
  get "/search/:category" => "pages#photos", as: "category"
  resources :users, except: [:edit] do
    resources :galleries
    resources :photos
    member do
      get :following, :followers
     end
  end

  get "/galleries/:id/photos/new" => "photos#new", :as => "new_gallery_photo"
  post "/galleries/:id/photos" => "photos#create", :as => "gallery_photos"
  get "/search" => "pages#photos"
  post "/photos" => "photos#create"

  resources :relationships, only: [:create, :destroy]

end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  visibility  :boolean
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Gallery < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :photos
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
 before_action :set_user, only: [:index, :show, :create, :edit, :update]
 before_action :set_gallery, only: [:edit, :update, :destroy]

  def index
    @galleries = @user.galleries
  end

  def new
    @user = @current_user
    @gallery = Gallery.new
  end

  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user = @user
      if @gallery.save
        redirect_to user_galleries_path
      else
        render :new
      end
  end

  def show
    @gallery = @user.galleries.find(params[:id])
  end

  def edit
  end

  def update
    @gallery.update(gallery_params)
    redirect_to user_gallery_path(@user, @gallery)
  end

  def destroy
    @gallery.destroy
    redirect_to user_galleries_path(@user)
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_gallery
    @user = @current_user
    @gallery = @user.galleries.find(params[:id])
  end

  def gallery_params
    params.require(:gallery).permit(:title, :description, :visibility, :user_id)
  end

end

app/helpers/galleries_helper.rb
module GalleriesHelper

end

app/views/galleries/_form.html.erb
<div class="container center">
<% unless @gallery.errors.full_messages.empty? %>
   <ul>
    <% @gallery.errors.full_messages.each do |e| %>
       <li><%= e %></li>
     <% end %>
   </ul>
 <% end %>
<div class="card-panel">


<%= form_for [@user, @gallery] do |f| %>
 <p>
  <%= f.label :title %>
  <%= f.text_field :title, :required => true %>
 </p>
 <p>
  <%= f.label :description %>
  <%= f.text_field :description%>
 </p>
 <%= f.submit class: "waves-effect waves-light btn" %>
<% end %>
</div>
</div>

app/views/galleries/edit.html.erb
<div class="container center">
<h3>Edit Gallery</h3>

<%= render 'form' %>
</div>

app/views/galleries/index.html.erb
<div class="center">
  <h3><%= @user.first_name%>'s Galleries</h3>
  <% if current_user?(@user) %>
    <p><%= link_to "Add New Gallery", new_user_gallery_path(@current_user), class:"waves-effects waves-light btn" %></p>
<% end %>
</div>

<div class="row">
<% @galleries.each do |g| %>
   <div class="col s4">
    <div class="card">
      <div class="card-image">
      <%= link_to( cl_image_tag(Photo.all.sample.image), user_gallery_path( @user, g) ) %>
      <span class="card-title"><%= g.title %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>

app/views/galleries/new.html.erb
<div class="container center">
<h3>New Gallery</h3>

<%= render 'form' %>

</div>

app/views/galleries/show.html.erb
<div class="center">
<h3><%= @gallery.title %></h3>
<% if current_user?(@user) %>
  <%= link_to "Delete Gallery", user_gallery_path(@user, @gallery), class:"waves-effects waves-light btn", :method => :delete,
    :data => {confirm: "Are you sure?"} %>
 <%= link_to "Edit Gallery", edit_user_gallery_path(@user, @gallery), class:"waves-effects waves-light btn" %>
 <%= link_to "Add Photo to Gallery", new_gallery_photo_path(@gallery), class:"waves-effects waves-light btn" %>
<% end %>
</div>
<div class="row">
<% @gallery.photos.each do |p| %>
   <div class="col s4">
    <div class="card">
      <div class="card-image">
      <%= link_to( cl_image_tag(p.image), user_photo_path( @user, p) ) %>
      <span class="card-title"><%= "#{p.title} - #{full_name(@user)}" %></span>
            </div>
          </div>
        </div>
    <% end %>
  </div>