config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "/home" => "pages#home"
  get "/galleries" => "pages#galleries"
  get "/photos" => "pages#photos"

  get "/login" => "sessions#new", as: :login
  post "/login" => "sessions#create"
  delete "/login" => "sessions#destroy"

  get "/users/edit" => "users#edit", as: "edit_user"
  get "/tag/:tag" => "pages#photos", as: :tag
  get "/search/:category" => "pages#photos", as: "category"
  resources :users, except: [:edit] do
    resources :galleries
    resources :photos
    member do
      get :following, :followers
     end
  end

  get "/galleries/:id/photos/new" => "photos#new", :as => "new_gallery_photo"
  post "/galleries/:id/photos" => "photos#create", :as => "gallery_photos"
  get "/search" => "pages#photos"
  post "/photos" => "photos#create"

  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_flash.html.erb
   <% if flash[:success] %>
      <h5 class="center"><%= flash[:success] %></h5>
    <% end %>
    <% if flash[:error] %>
      <h5 class="center"><%= flash[:error] %></h5>
    <% end %>

app/views/layouts/_footer.html.erb
  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a group of avid photographers trying to make the world a better place one photograph at a time.</p>

        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Connect</h5>
          <ul>
            <li><a class="white-text" href="#!">Facebook</a></li>
            <li><a class="white-text" href="#!">Twitter</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by me
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<!-- dropdown for categories -->
  <ul id="dropdown2" class="dropdown-content">
    <%categories.each do |c|%>
      <li><%= link_to "#{c.name}", category_path(c) %> </li>

    <!-- <li><%#= link_to "My Galleries", user_galleries_path(@current_user) %> </li> -->
  <% end %>
  </ul>

<!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
<% if @current_user.present? %>
    <li><%= link_to "My Profile", user_path(@current_user) %> </li>
    <li><%= link_to "My Galleries", user_galleries_path(@current_user) %> </li>
    <li><%= link_to "Manage Photos", user_photos_path(@current_user) %> </li>
    <li class="divider"></li>
    <li><%= link_to "Followers", followers_user_path(@current_user) %></li>
    <li><%= link_to "Following", following_user_path(@current_user) %> </li>
    <li class="divider"></li>
    <li><%= link_to "Logout" , login_path, :method => :delete %></li>
<% end %>
  </ul>
<nav class="teal lighten-1">
  <div class="nav-wrapper">
    <%=link_to "Maximum Exposure", root_path, class:"brand-logo"  %>
    <ul class="right hide-on-med-and-down">
      <% if @current_user.present? %>
      <li>
    <div class="nav-wrapper">
      <%= form_tag "/search", :method => "GET" do %>
        <label for="search"><i class="material-icons">search</i></label>
              <div class="input-field">
                <%= text_field_tag :tag %>
              </div>
            <% end %>

    </div>
      </li>
    <% end %>
      <% unless @current_user.present? %>
         <li><%= link_to "Login", login_path %> </li>
         <li><%= link_to "Sign Up", new_user_path %></li>
     <% else %>
        <li><%= link_to "Home", root_path %> </li>
        <li><%= link_to "Members", users_path %></li>
         <li><%= link_to "Galleries", galleries_path %> </li>
         <li><%= link_to "Photos", photos_path %> </li>
         <li><a class="dropdown-button" href="#!" data-activates="dropdown2">Categories<i class="material-icons right">arrow_drop_down</i></a></li>
         <!-- Dropdown Trigger -->
         <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><%= full_name(@current_user) %><i class="material-icons right">arrow_drop_down</i></a></li>
     <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Maximum Exposure</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <body>

   <%= render 'layouts/nav' %>
   <%= render 'layouts/flash' %>

 <main>
       <%= yield %>
 </main>

     <%= render 'layouts/footer' %>
 </body>
</html>